[build]
  # Directory to change to before starting a build
  base = "finobytes-dashboard"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "finobytes-dashboard/dist"
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index, follow"

# Enable compression for text-based resources
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Pre-compressed files (gzip)
[[headers]]
  for = "/*.js.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "text/html"
    Cache-Control = "public, max-age=0, must-revalidate"

# Pre-compressed files (brotli)
[[headers]]
  for = "/*.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "text/html"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SEO Headers
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# Environment variables (if needed)
[context.production.environment]
  VITE_ENV = "production"

[context.deploy-preview.environment]
  VITE_ENV = "preview"

[context.branch-deploy.environment]
  VITE_ENV = "development"
